version: "3.9"

services:
  apisix:
    image: apache/apisix:2.15.0-alpine
    volumes:
      - ./gateway/config.yml:/usr/local/apisix/conf/config.yaml:ro
      - ./gateway/apisix.yml:/usr/local/apisix/conf/apisix.yaml:ro
    ports:
      - "9000:9000"
      - "9080:9080"
  jaeger:
    image: jaegertracing/all-in-one:latest
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "16686:16686"
      - "4317:4317"
  catalog:
    build: ./catalog
    environment:
      APP_PRICING_ENDPOINT: http://pricing:5000/price
      OTEL_EXPORTER_OTLP_ENDPOINT: http://jaeger:4317
      OTEL_RESOURCE_ATTRIBUTES: service.name=catalog
      OTEL_METRICS_EXPORTER: none
      OTEL_LOGS_EXPORTER: none
  pricing:
    build: ./pricing
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: http://jaeger:4317
      OTEL_RESOURCE_ATTRIBUTES: service.name=pricing
      OTEL_METRICS_EXPORTER: none
      OTEL_LOGS_EXPORTER: none

